# Generated by Django 4.0.6 on 2022-08-20 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Review Details'),
        ),
    ]
