# Generated by Django 4.0.6 on 2022-08-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_ambulence_patient_alter_appointment_doctor_and_more'),
        ('services', '0007_alter_ambulence_patient'),
    ]

    operations = [
    ]
